### ISSUE TITLE
UITableView Doesn't Work in Foreground

### ISSUE THREAD

**Issue by vatsal1992** [wpsteak/PWParallaxScrollView#8]
in foreground, i added UIViews and in UIViews i added UITableView, when i run that code all things displays perfectly 
![3](https://cloud.githubusercontent.com/assets/12713108/8906209/48b3bb2a-348a-11e5-959c-c7dcacb5ab6c.jpg)
![4](https://cloud.githubusercontent.com/assets/12713108/8906211/48f8da5c-348a-11e5-8955-99792c5170d3.jpg)
![ios simulator screen shot 27-jul-2015 1 12 40 pm](https://cloud.githubusercontent.com/assets/12713108/8906210/48f54c2a-348a-11e5-9a2b-429a73842e4a.png)

but  when i touch on tableview, nothing happen on tableview...

**Comment by wpsteak** [comment]
You need to use UITableViewCellContentView instead of UITableView 
The solution is:

        if ([result isKindOfClass:NSClassFromString(@"UITableViewCellContentView")]){

            return result;

        }

**Comment by a-radwan** [comment]
Not only table view, Gestures are not working in any view at foreground view.
Any solution?
